http:
  listener:
    host: "localhost"
    port: "8081"
    path: "/travelontipcall/{serviceType}"
    
db:
 oracle:
   host: "localhost"
   port: "1521"
   user: "dummy"
   password: "dummy"
   instance: ""
   service: "ORCLCDB.localdomain"
 